### ISSUE TITLE
一个好奇的问题

### ISSUE THREAD

**Issue by JIMhackKING** [ieiayaobb/lushi8#1]
我一直纠结，一直好奇，一直找不到，全民直播的那个JSON怎么找到的……

**Comment by ieiayaobb** [comment]
我看了一下现在的加载方式，好像也是后台渲染出来的。
估计当时我在处理的时候是一个AJAX的请求，然后现在虽然改了加载方式，但是他那个接口还保留了吧。
回去我再仔细研究一下

**Comment by JIMhackKING** [comment]
哈哈，好的，现在的加载方式我找了很久都找不到后台渲染出来的数据，所以那一部分我只好用bs4解析页面

**Comment by JIMhackKING** [comment]
我找到了那个api，触发条件是用手机登录的时候网页跳转至m.quanmin.tv，这个时候就会请求那个api

**Comment by ieiayaobb** [comment]
厉害，是不是其他直播网站在wap方式访问的时候都有json接口的，那就方便多了，哈哈，回头试试看

**Comment by JIMhackKING** [comment]
应该不是都有json接口的，用到ajax的网站才有json接口，我只找到了三个网站使用json接口的，我也弄了个LOL的直播视频聚合，哈哈，在我github上
